apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
        - name: log-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "{{ .Values.postgres.host }}"
            - name: DB_USER
              value: "{{ .Values.postgres.user }}"
            - name: DB_PASS
              value: "{{ .Values.postgres.password }}"
            - name: DB_NAME
              value: "{{ .Values.postgres.db }}"

