image:
  repository: docker.io/igalla
  tag: d55b69bf583c5a499e8b6e3c6cc221855606661c
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

