image:
  repository: docker.io/igalla
  tag: fe4afe409c30aba5a9b882fecb7f98bb5dc5f1ed
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

