image:
  repository: docker.io/igalla
  tag: 92ef9637ace344d2b45bbce90c1579c86d1e874e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

