image:
  repository: docker.io/igalla
  tag: ed551973d27eff1f4455b0a471833e70d977e8e1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

