image:
  repository: docker.io/igalla
  tag: 453e66b3a310dd85c2bc0d2d4e13d2324838d44a
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

