image:
  repository: docker.io/igalla
  tag: d8a28c644bc83e70070c2c2648128c93ce0fe8fe
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

postgres:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  db: "logs"

