name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: log-cluster
  GKE_ZONE: me-west1-a
  GCP_PROJECT_ID: effortless-cat-455311-h2
  DEPLOYMENT_NAME: log-collector
  NAMESPACE: log-dev
  IMAGE_NAME: igalla/log-collector

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk:slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Set up gcloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure gcloud
      run: |
        gcloud config set project $GCP_PROJECT_ID
        gcloud config set compute/zone $GKE_ZONE
        gcloud container clusters get-credentials $GKE_CLUSTER

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin


    - name: Deploy to GKE via Helm
      run: |
        helm upgrade --install $DEPLOYMENT_NAME . \
          --namespace $NAMESPACE \
          -f values-dev.yaml \
          --set image.repository=docker.io/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ github.sha }}

