name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: log-cluster
  GKE_ZONE: me-west1-a
  GCP_PROJECT_ID: effortless-cat-455311-h2
  DEPLOYMENT_NAME: log-collector
  NAMESPACE: log-dev
  IMAGE_NAME: igalla/log-collector

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with push access
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push docker.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Update values-dev.yaml with new image tag
      run: |
        sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" values-dev.yaml
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add values-dev.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push origin main
        fi

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Activate service account
      run: |
        gcloud config set account ${{ fromJson(secrets.GCP_CREDENTIALS).client_email }}

    - name: Get GKE credentials
      run: |
        gcloud config set compute/zone $GKE_ZONE
        gcloud container clusters get-credentials $GKE_CLUSTER

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy with Helm
      run: |
        helm upgrade --install $DEPLOYMENT_NAME . \
          --namespace $NAMESPACE \
          -f values-dev.yaml \
          --set image.repository=docker.io/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ github.sha }}
